構成を大幅更新

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -18,22 +18,23 @@ is_exists() {
 }
 
 install_build_tool() {
-    . ${DOTFILESPATH}/bin/lib/os_detect.sh
+    . ${DOTFILES}/etc/scripts/lib/os_detect.sh
     OS=$(os_detect)
 
     # makeが存在しないと後続が続かないので
     if [ ${OS} == 'linux' ]; then
+      if ! is_exists "make"; then
         sudo apt update
         sudo apt upgrade
         sudo apt install -y build-essential
+      fi
     fi
 }
 
 # ==============================
 
-DOTFILESPATH=~/.dotfiles
 GITHUB_URL=https://github.com/knsugiyama/dotfiles.git
-DOTFILES=~/.dotfiles;
+DOTFILES=~/.dotfiles; export DOTPATH
 
 download() {
   if ! is_exists "curl" && ! is_exists "wget"; then
@@ -57,14 +58,50 @@ download() {
   install_build_tool
 }
 
-download
+deploy() {
+    if [ ! -d $DOTFILES ]; then
+        log_fail "$DOTFILES: not found"
+        exit 1
+    fi
+    cd "$DOTFILES"
+    make deploy
+}
+
+initialize() {
+  local path install_shell
+  if [ ${OS} == 'linux' ]; then
+    path=${DOTFILES}/etc/init/linux
+  elif [ ${OS} == 'osx']; then
+    path=${DOTFILES}/etc/init/mac
+  else
+    log_fail "Out of support OS"
+    exit 1
+  fi
+
+  cat ${path}/installation-order | while read install_shell;
+  do
+  if [ line != '' ]; then
+      echo $(log_info "runnning shell name: $install_shell")
+      sh -c "${install_shell}"
+      . ~/.bash_profile
+  fi
+  done
+}
+
+install() {
+  download &&
+  deploy &&
+  initialize
+}
+
+install
 
 # ディレクトリの削除
 if [ -d ~/.config ]; then
     rm -rf ~/.config
 fi
 
-# git管理できるように
+# git管理できるようにする
 cd "$DOTFILES"
 git init
 git remote add origin "$GITHUB_URL"
